server:
    port: 8888

spring:
#    profiles:
#        active: native
#        cloud:
#            config:
#                server:
#                    native:
#                        searchLocations: classpath:/config,file:${server-location},file:///${Linux-pc-location},file:///${windows-pc-location},file:///${mac-pc-location}
    application:
        name: configuration-management-server
    jmx:
        default-domain: configuration-management-server
    security:
        user:
            name: ilan
            password: ilan
    cloud:
        config:
            server:
                git:
                    force-pull: true
                    search-paths: Accused,Crime,WebFlux-Producer,WebFlux-Consumer
                    skip-ssl-validation: true
                    timeout: 4
                    uri: https://github.com/ILANKUMARAN11/ConfigServer_AppProperties.git
                    username:
                    password:
    boot:
        ######################## Spring Boot Admin configuration ########################
        admin:
            auto-deregistration: false
            auto-registration: true
            client:
                enabled: true
            password: admin
            register-once: false
            url: http://localhost:8077
            username: admin

######################## ACTUATOR ########################
management:
    endpoint:
        #Whether to exposure all endpoints by default
        enabled-by-default: false
        #If all endPoints where disable by default, so we have to decide endpoints like info, metrics to be enabled
        info:
            enabled: true
        metrics:
            enabled: true
        shutdown:
            enabled: true
    endpoints:
        jmx:
            exposure:
                include: '*'
                #exclude: '*'
        web:
            exposure:
                include: info,health,refresh,env
                #exclude: '*'

######################## Eureka Server Configuration ########################
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        lease-renewal-interval-in-seconds: 10





Linux-pc-location: /root/SpringBoot/config
mac-pc-location: /ILAN/ConfigServer_Props/config
windows-pc-location: C:/ILAN/OnSite/config
server-location: /jboss/FB/config-property
