eureka:
    client:
        fetch-registry: true
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
        hostname: localhost
server:
    port: 8761
spring:
    application:
        name: service-registry-server
    boot:
        admin:
            auto-deregistration: false
            auto-registration: true
            client:
                enabled: true
            password: admin
            register-once: false
            url: http://localhost:8077
            username: admin
    jmx:
        default-domain: service-registry-server
